// @ts-nocheck
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
// @ts-ignore
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  engine: "library",
  datasource: {
    url: env("DB_URL_OFFICIAL"),
  },
});
